language: node_js
sudo: false
node_js:
  - "6.10.3"

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-6-dev

env:
  global:
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CC="clang"
    - CXX="clang++"
    - HOST_OS="$(if [ "$TRAVIS_OS_NAME" == "osx" ]; then echo "darwin"; else echo "$TRAVIS_OS_NAME")"
  matrix:
    - TARGET_ARCH=x64
    - TARGET_ARCH=x86

matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: TARGET_ARCH=x86

os:
  - linux
  - osx

install:
  - travis_wait ./scripts/ci/install.sh -o $HOST_OS -r $TARGET_ARCH

script:
  - ./scripts/ci/test.sh -o $HOST_OS -r $TARGET_ARCH

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/ci/deploy.sh -o $HOST_OS -r $TARGET_ARCH
  on:
    branch: master

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a019c8b9828eb9f6a72
    on_success: change
    on_failure: always
    on_start: never
